USER_BASE_ROUTE = "/users"

LOGIN_ROUTE = "/login"
REGISTER_ROUTE = "/register"

LOGIN_FULL_ROUTE = f"{USER_BASE_ROUTE}{LOGIN_ROUTE}"
REGISTER_FULL_ROUTE = f"{USER_BASE_ROUTE}{REGISTER_ROUTE}"

STATION_BASE_ROUTE = "/stations"

ALL_STATIONS_ROUTE = "/"
CREATE_A_STATION_ROUTE = "/"
ADD_NEW_STATION_ROUTE = "/"
RESET_STATION_KEY_ROUTE = "/reset"
GET_A_STATION_ROUTE = "/{stationName}"

RECORD_ROUTE_BASE = "/records"

CREATE_RECORD_ROUTE = "/"
GET_THE_LATEST_RECORD_ROUTE = "/{stationId}/latest"

CREATE_RECORD_FULL_ROUTE = f"{RECORD_ROUTE_BASE}{CREATE_RECORD_ROUTE}"
GET_THE_LATEST_RECORD_FULL_ROUTE = f"{RECORD_ROUTE_BASE}{GET_THE_LATEST_RECORD_ROUTE}"

ALL_STATIONS_FULL_ROUTE = f"{STATION_BASE_ROUTE}{ALL_STATIONS_ROUTE}"
CREATE_A_STATION_FULL_ROUTE = f"{STATION_BASE_ROUTE}{CREATE_A_STATION_ROUTE}"
ADD_NEW_STATION_FULL_ROUTE = f"{STATION_BASE_ROUTE}{ADD_NEW_STATION_ROUTE}"
RESET_STATION_KEY_FULL_ROUTE = f"{STATION_BASE_ROUTE}{RESET_STATION_KEY_ROUTE}"
GET_A_STATION_FULL_ROUTE = f"{STATION_BASE_ROUTE}{GET_A_STATION_ROUTE}"
