STATION_NAME_KEY = "stationName"
STATION_STATION_KEY_KEY = "stationKey"
STATION_POSITION_KEY = "stationPosition"
PUSHING_DATA_INTERVAL_IN_SECONDS_KEY = "pushingDataIntervalInSeconds"
USERNAME_KEY = "username"
PASSWORD_KEY = "password"
USER_KEY = "user"
TOKEN_KEY = "token"
USERID_KEY = "userId"
WEATHER_DATA_KEY = "record"
AUTHORIZATION_KEY = "Authorization"


STATUS_CODE_KEY = "status_code"
DETAIL_KEY = "detail"


HTTP_200_OK = 200
HTTP_404_NOT_FOUND = 404
HTTP_409_CONFLICT = 409
HTTP_401_UNAUTHORIZED = 401
HTTP_400_BAD_REQUEST = 400

