from app.constants import (
    STATUS_CODE_KEY,
    DETAIL_KEY,
)


HAVE_NO_PERMISSION_STATUS_CODE = 401 
HAVE_NO_PERMISSION_DETAIL = "Have no permission."

HAVE_NO_PERMISSION_STATUS = {
    STATUS_CODE_KEY: HAVE_NO_PERMISSION_STATUS_CODE,
    DETAIL_KEY: HAVE_NO_PERMISSION_DETAIL
}
