from app.exceptions import (
    STATUS_CODE_KEY,
    DETAIL_KEY,
)


STATION_EXIST_STATUS_CODE = 409
STATION_EXIST_DETAIL = "The station exists."


STATION_EXIST_STATUS = {
    STATUS_CODE_KEY: STATION_EXIST_STATUS_CODE,
    DETAIL_KEY: STATION_EXIST_DETAIL
}
