from app.exceptions import (
    STATUS_CODE_KEY,
    DETAIL_KEY,
    HTTP_409_CONFLICT
)


STATION_EXIST_STATUS_CODE = HTTP_409_CONFLICT
STATION_EXIST_DETAIL = "The station exists."


STATION_EXIST_STATUS = {
    STATUS_CODE_KEY: STATION_EXIST_STATUS_CODE,
    DETAIL_KEY: STATION_EXIST_DETAIL
}
