from app.exceptions import (
    STATUS_CODE_KEY,
    DETAIL_KEY,
)


UNAUTHORIZATION_STATUS_CODE = 401
UNAUTHORIZATION_DETAIL = "Unauthorization"

UNAUTHORIZATION_STATUS = {
    STATUS_CODE_KEY: UNAUTHORIZATION_STATUS_CODE,
    DETAIL_KEY: UNAUTHORIZATION_DETAIL
}
