from app.constants import (
    STATUS_CODE_KEY,
    DETAIL_KEY,
    HTTP_401_UNAUTHORIZED
)


UNAUTHORIZATION_STATUS_CODE = HTTP_401_UNAUTHORIZED
UNAUTHORIZATION_DETAIL = "Unauthorization"

UNAUTHORIZATION_STATUS = {
    STATUS_CODE_KEY: UNAUTHORIZATION_STATUS_CODE,
    DETAIL_KEY: UNAUTHORIZATION_DETAIL
}
