from app.constants import (
    STATUS_CODE_KEY,
    DETAIL_KEY,
    HTTP_404_NOT_FOUND,
)


WRONG_PASSWORD_STATUS_CODE = HTTP_404_NOT_FOUND
WRONG_PASSWORD_DETAIL = "The password is wrong."


WRONG_PASSWORD_STATUS = {
    STATUS_CODE_KEY: WRONG_PASSWORD_STATUS_CODE,
    DETAIL_KEY: WRONG_PASSWORD_DETAIL
}
