from app.exceptions import (
    STATUS_CODE_KEY,
    DETAIL_KEY,
)


WRONG_PASSWORD_STATUS_CODE = 404
WRONG_PASSWORD_DETAIL = "The password is wrong."


WRONG_PASSWORD_STATUS = {
    STATUS_CODE_KEY: WRONG_PASSWORD_STATUS_CODE,
    DETAIL_KEY: WRONG_PASSWORD_DETAIL
}
