from app.exceptions import (
    STATUS_CODE_KEY,
    DETAIL_KEY,
)


WRONG_STATION_KEY_STATUS_CODE = 400
WRONG_STATION_KEY_DETAIL = "The stationKey is incorrect."

WRONG_STATION_KEY_STATUS = {
    STATUS_CODE_KEY: WRONG_STATION_KEY_STATUS_CODE,
    DETAIL_KEY: WRONG_STATION_KEY_DETAIL
}
